In [9]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [10]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1, 2)

print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1, 6)

print(newarr)

[[1 2 3 4 5 6]]


In [19]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape(2, 2, 4)
print(reshaped)
len(reshaped),len(reshaped[0]),len(reshaped[0][0])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


(2, 2, 4)

In [22]:
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# converting it to 1-D from 2-D array
reshaped = array.reshape((9))
print(reshaped)

[1 2 3 4 5 6 7 8 9]
